"""empty message

Revision ID: 697cd4a300bf
Revises: 
Create Date: 2019-02-18 20:38:12.750148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697cd4a300bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('primary_emotion', sa.String(length=255), nullable=True),
    sa.Column('secondary_emotion', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Moods')
    # ### end Alembic commands ###
