"""empty message

Revision ID: a13c6e1d693f
Revises: 697cd4a300bf
Create Date: 2019-02-18 20:39:46.808020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a13c6e1d693f'
down_revision = '697cd4a300bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('primary_emotion', sa.String(length=255), nullable=True),
    sa.Column('secondary_emotion', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Moods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Moods',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Moods_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('primary_emotion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secondary_emotion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Moods_pkey')
    )
    op.drop_table('moods')
    # ### end Alembic commands ###
